#!/bin/bash
# PostToolUse: after an edit to a task file or the generated index, re-check the
# task graph and feed problems back to the agent (exit 2 = blocking feedback).
#
# Matches on tool_input.file_path only. Matching the whole payload — the v1 bug —
# also fires on any file whose *content* merely mentions the path.

set -uo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
INPUT="$(cat)"

FILE_PATH="$(printf '%s' "$INPUT" | python3 -c '
import json, sys
try:
    print(json.load(sys.stdin).get("tool_input", {}).get("file_path", ""))
except Exception:
    print("")
')"

case "$FILE_PATH" in
  *docs/tasks/tasks/*.md|*docs/tasks/tasks.md) ;;
  *) exit 0 ;;
esac

# The index is generated; a hand-edit is silently lost on the next status change.
case "$FILE_PATH" in
  *docs/tasks/tasks.md)
    echo "docs/tasks/tasks.md is generated by 'python3 scripts/tasks.py index'." >&2
    echo "Edit the task files in docs/tasks/tasks/ instead — this change will be overwritten." >&2
    exit 2
    ;;
esac

if ! OUTPUT="$(python3 "$REPO_ROOT/scripts/tasks.py" validate 2>&1)"; then
  echo "Task graph is inconsistent after your edit:" >&2
  echo "$OUTPUT" >&2
  echo "Fix these. Use 'python3 scripts/tasks.py status|evidence' for status and evidence." >&2
  exit 2
fi
exit 0
